
[package]
name = "schema-inference"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "flow-schema-inference"
path = "src/main.rs"

[dependencies]
doc = { path = "../doc", version = "0.0.0" }
json = { path = "../json", version = "0.0.0" }
journal-client = { path = "../journal-client", version = "0.0.0" }
assemble = { path = "../assemble", version = "0.0.0" }
models = { path = "../models", version = "0.0.0" }
proto-gazette = { path = "../proto-gazette" }

anyhow = {workspace=true}
clap = {workspace=true}
itertools = {workspace=true}
schemars ={workspace=true}
serde = {workspace=true}
serde_json = {workspace=true}
tonic = {workspace=true}
tokio = {workspace=true}
tracing = {workspace=true}
tracing-subscriber ={workspace=true}
prost = {workspace=true}
thiserror = {workspace=true}
tokio-util ={workspace=true}
futures-util ={workspace=true}
futures = {workspace=true}
bytes ={workspace=true}

[dev-dependencies]
insta = {workspace=true}

[build-dependencies]
tonic-build = {workspace=true}
